### PR TITLE
Fix #235: Unable to access docker daemon from host

### LINKED ISSUE #235: Unable to access docker daemon from host with latest master code
Hi,

On using master branch and installing plugin, I am not able to access docker daemon from host.

Logs:

```
➜  vagrant-service-manager git:(master) ✗  bundle exec vagrant up --provider virtualbox
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'projectatomic/adb'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: vagrant-service-manager_default_1464362815699_72957
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: No guest additions were detected on the base box for this VM! Guest
    default: additions are required for forwarded ports, shared folders, host only
    default: networking, and more. If SSH fails on this machine, please install
    default: the guest additions and repackage the box to continue.
    default: 
    default: This is not an error message; everything may continue to work properly,
    default: in which case you may ignore this message.
==> default: When using virtualbox, a non-NAT network interface is required.
==> default: Adding a private network using DHCP
==> default: Copying TLS certificates to /home/budhram/redhat/vagrant-service-manager/.vagrant/machines/default/virtualbox/docker
==> default: Rsyncing folder: /home/budhram/redhat/vagrant-service-manager/ => /vagrant

➜  vagrant-service-manager git:(master) ✗ bundle exec vagrant service-manager env docker            
# Set the following environment variables to enable access to the
# docker daemon running inside of the vagrant virtual machine:
export DOCKER_HOST=tcp://10.0.2.15:2376
export DOCKER_CERT_PATH=/home/budhram/redhat/vagrant-service-manager/.vagrant/machines/default/virtualbox/docker
export DOCKER_TLS_VERIFY=1
export DOCKER_API_VERSION=1.21

# run following command to configure your shell:
# eval "$(vagrant service-manager env docker)"

➜  vagrant-service-manager git:(master) ✗ export DOCKER_HOST=tcp://10.0.2.15:2376
export DOCKER_CERT_PATH=/home/budhram/redhat/vagrant-service-manager/.vagrant/machines/default/virtualbox/docker
export DOCKER_TLS_VERIFY=1
export DOCKER_API_VERSION=1.21

➜  vagrant-service-manager git:(master) ✗ docker images
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

### PR DESCRIPTION
**Pull request by brgnepal**
Fix #235.

Reason:
[This fix](https://github.com/budhrg/vagrant-service-manager/blob/a06699468912d3450ba32192e6fd9ab2a6509338/lib/vagrant-service-manager/action/setup_network.rb#L13) allowed the continuation of executing middlewares before setting up private network.

Executing private network after `@app.call(env)` made all middlewares executed first along with "service" execution hook.

### CODE REVIEW

File: lib/vagrant-service-manager/action/setup_network.rb [hunk 1]
```diff
@@ -10,11 +10,11 @@ def initialize(app, env)
         end
 
         def call(env)
-          @app.call(env)
-
-          if SUPPORTED_BOXES.include? @machine.guest.capability(:os_variant)
+          if SUPPORTED_BOXES.include? @machine.config.vm.box.sub('projectatomic/', '')
```
Comment (navidshaikh) [inline lib/vagrant-service-manager/action/setup_network.rb]: If user has added the box manually with different name, this check will fail.

```
$ vagrant box add foobar <path/to/box_file>
# Vagrantfile will have foobar as the box name and check can fail
```

Comment (brgnepal) [inline lib/vagrant-service-manager/action/setup_network.rb]: Agree. This implementation make hard dependency on box name for the use of plugin.

Comment (hferentschik) [inline lib/vagrant-service-manager/action/setup_network.rb]: where is the ' @app.call(env)' call? You need to continue the chain, right? Why did you do it on the up chain anyways?
