### PR TITLE
Fix #257: proper error message on restarting a stopped service

### LINKED ISSUE #257: Need proper error message on restarting a stopped service
$ vagrant service-manager restart kubernetes
The folowing SH comand responded with a non-zero exit status.
Vagrant asumes that this means the comand failed!
scli kubernetes restart
Stdout from the comand:
Stder from the comand:
Start kubernetes first

Stdout, stderr and sccli details are printed on the screen when restarting a stopped service. Error message could be more meaningful.

### PR DESCRIPTION
**Pull request by brgnepal**
Fix #257 

Patched gem: https://www.dropbox.com/s/ytkrfc0f4ru3mma/vagrant-service-manager-1.4.0.dev.gem.

Please verify @pavanbhat21 and @amitkrout

### CODE REVIEW

**Comment by pavanbhat21** [comment]
I tried on my fedora machine, LGTM.

**Comment by brgnepal** [comment]
@navidshaikh Rebased with upstream master.

**Comment by navidshaikh** [comment]
LGTM

File: lib/vagrant-service-manager/command.rb [hunk 1]
```diff
@@ -248,6 +248,13 @@ def perform_service(operation, service)
             PluginUtil.generate_kubeconfig(machine, @env.ui, File.dirname(ServiceManager.bin_dir))
           end
         end
+      rescue StandardError => e
+        if operation == 'restart' && e.message.include?("Start #{service} first")
+          @env.ui.error I18n.t('servicemanager.commands.operation.start_service_first')
+          return
```
Comment (navidshaikh) [inline lib/vagrant-service-manager/command.rb]: if an operation can not be performed, the exit code should be `126`

Comment (navidshaikh) [inline lib/vagrant-service-manager/command.rb]: just like in a standard system, a stopped service can be started with `restart` or `start` operation, we should consider `restart` option on a stopped service as well.

Comment (brgnepal) [reply lib/vagrant-service-manager/command.rb]: @navidshaikh Since, sccli is not offering that feature, we are forced to come up with messaging at present.

**Comment by brgnepal** [comment]
@navidshaikh Updated as per suggestions.

**Comment by navidshaikh** [comment]
The right fix for the issue would be to start the kubernetes service even if it is stopped (and openshift is also  stoppped as well) and user has commanded `vagrant service-manager restart kubernetes`, the service should start.

Lets hold till we have a decision on https://github.com/projectatomic/adb-utils/issues/157

**Comment by navidshaikh** [comment]
As discussed, lets get this PR in and wait for support from `sccli` https://github.com/projectatomic/adb-utils/issues/157 .

**Comment by navidshaikh** [comment]
LGTM
