### PR TITLE
Check exit code instead of "stderr" stream

### LINKED ISSUE #160: "vagrant service-manager restart openshift" not working as expected
vagrant-service-manager (1.0.0)
ADB 1.8.0

"vagrant service-manager restart openshift"  is causing the OpenShift service  go to failed state.
- Before beginning th test, I verified that OpenShift was running fine.

``` r
[vagrant@centos7-adb ~]$ sudo systemctl status openshift
● openshift.service - Docker Application Container for OpenShift
   Loaded: loaded (/usr/lib/systemd/system/openshift.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2016-04-07 13:49:00 EDT; 20s ago
     Docs: https://docs.openshift.org/
 Main PID: 16335 (sh)
   CGroup: /system.slice/openshift.service
           ├─16335 /usr/bin/sh /opt/adb/openshift/openshift
           └─16361 docker run --name openshift --privileged --net=host --pid=host -w /var/lib/openshift -e KUBECONFIG=/var/lib/openshift/openshift.local.config/master/admin.kubeconfig -v /:/rootfs:ro -v /var/...

Apr 07 13:48:59 centos7-adb sh[16336]: error: deploymentconfigs/docker-registry volume mount '/etc/secrets' already exists for container 'registry'
Apr 07 13:48:59 centos7-adb sh[16335]: W0407 17:48:59.893049   16401 manager.go:1930] Hairpin setup failed for pod "docker-registry-2-i69k6_default(8e6f7ce4-fce4-11e5-a17a-52540047d72c)": open ...nly file system
Apr 07 13:48:59 centos7-adb sh[16336]: deploymentconfig "docker-registry" updated
Apr 07 13:49:00 centos7-adb sh[16336]: The DeploymentConfig "docker-registry" is invalid.
Apr 07 13:49:00 centos7-adb sh[16336]: * spec.template.spec.containers[0].livenessProbe.httpGet.scheme: Invalid value: "HTTPSS": must be one of [HTTP HTTPS]
Apr 07 13:49:00 centos7-adb sh[16336]: * spec.template.spec.containers[0].readinessProbe.httpGet.scheme: Invalid value: "HTTPSS": must be one of [HTTP HTTPS]
Apr 07 13:49:00 centos7-adb sh[16336]: route "docker-registry" replaced
Apr 07 13:49:00 centos7-adb systemd[1]: Started Docker Application Container for OpenShift.
Apr 07 13:49:00 centos7-adb sh[16335]: I0407 17:49:00.750778   16401 provider.go:91] Refreshing cache for provider: *credentialprovider.defaultDockerConfigProvider
Apr 07 13:49:14 centos7-adb systemd[1]: Started Docker Application Container for OpenShift.
Hint: Some lines were ellipsized, use -l to show in full.
```
- Then executed `$ vagrant service-manager restart openshift`  and observed that OpenShift went to failed state.

``` r
[vagrant@centos7-adb ~]$ sudo systemctl status openshift
● openshift.service - Docker Application Container for OpenShift
   Loaded: loaded (/usr/lib/systemd/system/openshift.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: https://docs.openshift.org/

Apr 08 00:58:59 centos7-adb sh[14446]: openshift
Apr 08 00:58:59 centos7-adb systemd[1]: openshift.service: main process exited, code=exited, status=143/n/a
Apr 08 00:58:59 centos7-adb sh[14446]: d4132086bbec
Apr 08 00:58:59 centos7-adb sh[14446]: 7182c1f4f519
Apr 08 00:58:59 centos7-adb sh[14446]: fdb6deadd67c
Apr 08 00:58:59 centos7-adb sh[14446]: 7d4357c91254
Apr 08 00:59:00 centos7-adb sh[14446]: 96f2bb233d64
Apr 08 00:59:00 centos7-adb systemd[1]: Stopped Docker Application Container for OpenShift.
Apr 08 00:59:00 centos7-adb systemd[1]: Unit openshift.service entered failed state.
Apr 08 00:59:00 centos7-adb systemd[1]: openshift.service failed.
```
- However running `sccli openshift` working is fine and fix the failed state of OpenShift.

``` r
[vagrant@centos7-adb ~]$ sccli openshift
Stopping the Openshift services
Removed symlink /etc/systemd/system/multi-user.target.wants/openshift.service.
Trying to pull repository docker.io/openshift/origin ... v1.1.3: Pulling from openshift/origin
Digest: sha256:7a23c8efbed8166444aaa69a92790f78efded841c0eaae905976a493dd165d76
Status: Image is up to date for docker.io/openshift/origin:v1.1.3

Trying to pull repository docker.io/openshift/origin-haproxy-router ... v1.1.3: Pulling from openshift/origin-haproxy-router
Digest: sha256:9e714a9ed6da62bb8a14c15db084dc659842aba6dc66b4a9cf121d24101b1ac9
Status: Image is up to date for docker.io/openshift/origin-haproxy-router:v1.1.3

Trying to pull repository docker.io/openshift/origin-deployer ... v1.1.3: Pulling from openshift/origin-deployer
Digest: sha256:882745cc3a24545208a59415e59fb982e4e57cfdf5dadc4617c273a79301eb24
Status: Image is up to date for docker.io/openshift/origin-deployer:v1.1.3

Trying to pull repository docker.io/openshift/origin-docker-registry ... v1.1.3: Pulling from openshift/origin-docker-registry
Digest: sha256:ef09b31a152bd16405cd56c9a3b817a2cbc0f5bea369da19ecde109a2a03551c
Status: Image is up to date for docker.io/openshift/origin-docker-registry:v1.1.3

Trying to pull repository docker.io/openshift/origin-sti-builder ... v1.1.3: Pulling from openshift/origin-sti-builder
Digest: sha256:5c57850227568a67a0faa76a1993dfc7aaa2f034ebb43e5dc3d201314367e772
Status: Image is up to date for docker.io/openshift/origin-sti-builder:v1.1.3

Created symlink from /etc/systemd/system/multi-user.target.wants/openshift.service to /usr/lib/systemd/system/openshift.service.


[vagrant@centos7-adb ~]$ sudo systemctl status openshift
● openshift.service - Docker Application Container for OpenShift
   Loaded: loaded (/usr/lib/systemd/system/openshift.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2016-04-08 01:02:38 EDT; 15s ago
     Docs: https://docs.openshift.org/
  Process: 15515 ExecStartPost=/usr/bin/sh /opt/adb/openshift/openshift_provision (code=exited, status=0/SUCCESS)
  Process: 15507 ExecStartPre=/usr/bin/docker rm openshift (code=exited, status=0/SUCCESS)
  Process: 15503 ExecStartPre=/usr/bin/docker stop openshift (code=exited, status=0/SUCCESS)
 Main PID: 15514 (sh)
   Memory: 64.0K
   CGroup: /system.slice/openshift.service
           ├─15514 /usr/bin/sh /opt/adb/openshift/openshift
           └─15544 docker run --name openshift --privileged --net=host --pid=host -w /var/lib/openshift -e KUBECONFIG=/var/lib/openshift/openshift.local.config/master/admin.kubeconfig -v /:/rootfs:ro -v /var/...

Apr 08 01:02:37 centos7-adb sh[15515]: error: deploymentconfigs/docker-registry volume mount '/etc/secrets' already exists for container 'registry'
Apr 08 01:02:37 centos7-adb sh[15514]: I0408 05:02:37.621087   15580 manager.go:254] Recovery completed
Apr 08 01:02:37 centos7-adb sh[15515]: deploymentconfig "docker-registry" updated
Apr 08 01:02:38 centos7-adb sh[15515]: The DeploymentConfig "docker-registry" is invalid.
Apr 08 01:02:38 centos7-adb sh[15515]: * spec.template.spec.containers[0].livenessProbe.httpGet.scheme: Invalid value: "HTTPSS": must be one of [HTTP HTTPS]
Apr 08 01:02:38 centos7-adb sh[15515]: * spec.template.spec.containers[0].readinessProbe.httpGet.scheme: Invalid value: "HTTPSS": must be one of [HTTP HTTPS]
Apr 08 01:02:38 centos7-adb sh[15515]: route "docker-registry" replaced
Apr 08 01:02:38 centos7-adb systemd[1]: Started Docker Application Container for OpenShift.
Apr 08 01:02:38 centos7-adb sh[15514]: W0408 05:02:38.485664   15580 manager.go:1930] Hairpin setup failed for pod "docker-registry-2-i69k6_default(8e6f7ce4-fce4-11e5-a17a-52540047d72c)": open ...nly file system
Apr 08 01:02:39 centos7-adb sh[15514]: I0408 05:02:39.101593   15580 provider.go:91] Refreshing cache for provider: *credentialprovider.defaultDockerConfigProvider
Hint: Some lines were ellipsized, use -l to show in full.
```

### LINKED ISSUE #163: For CDK vagrant-service-manager should print OpenShift setup information during `vagrant up`
Vagrant-service-manager (1.0.0) should print OpenShift setup information during `vagrant up` for CDK. 

For CDK,  vagrant-service-manager  should print the below OpenShift information as it is the default in CDK.

```
==> default: 
==> default: Successfully started and provisioned VM with 2 cores and 3072 MB of memory.
==> default: To modify the number of cores and/or available memory set the environment variables
==> default: VM_CPU respectively VM_MEMORY.
==> default: 
==> default: You can now access the OpenShift console on: https://10.1.2.2:8443/console
==> default: 
==> default: To use OpenShift CLI, run:
==> default: $ vagrant ssh
==> default: $ oc login 10.1.2.2:8443
==> default: 
==> default: Configured users are (<username>/<password>):
==> default: openshift-dev/devel
==> default: admin/admin
==> default: 
==> default: If you have the oc client library on your host, you can also login from your host.
```

### LINKED ISSUE #166: For CDK box, provisioners are not executed by default on Vagrant up
Hi,

On using [this Vagrantfile](https://github.com/projectatomic/adb-atomic-developer-bundle/blob/master/components/rhel/rhel-ose/Vagrantfile#L55), shell provisioners listed in the Vagrantfile is not executing by default on `Vagrant up` step.

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

....
Vagrant.configure(2) do |config|
  config.vm.box = 'cdkv2'

  config.vm.provider "virtualbox" do |v, override|
    v.memory = 2048
    v.cpus   = 2
    v.customize ["modifyvm", :id, "--cpus", "2"]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end
.....
 ....
  config.vm.network "private_network", ip: "#{PUBLIC_ADDRESS}"
....
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    echo "You can now access OpenShift console on: https://#{PUBLIC_ADDRESS}:8443/console"
    echo
    echo "Configured basic user: openshift-dev, Password: devel"
    echo
    echo "Configured cluster admin user: admin, Password: admin"
    echo
    echo "To use OpenShift CLI, run:"
    echo "$ vagrant ssh"
    echo "$ oc login"
    echo
    echo "To browse the OpenShift API documentation, follow this link:"
    echo "http://openshift3swagger-claytondev.rhcloud.com"
    echo
    echo "Then enter this URL:"
    echo https://#{PUBLIC_ADDRESS}:8443/swaggerapi/oapi/v1
    echo "."
  SHELL
end
```

### PR DESCRIPTION
**Pull request by brgnepal**
Fixes #160 and #166

```
* Fixes #160: "vagrant service-manager restart openshift" not working
* Fixes #166: For CDK box, provisioners are not executed by default on Vagrant up
```

### CODE REVIEW

File: lib/vagrant-service-manager/command.rb [hunk 1]
```diff
@@ -266,21 +266,21 @@ def print_vagrant_box_version(script_readable = false)
...
+        command = if SCCLI_SERVICES.include? service
+                    # TODO : Handle the case where user wants to pass extra
+                    # arguments to OpenShift service
+                    "sccli #{service}"
+                  else
+                    "systemctl restart #{service}"
+                  end
+
+        with_target_vms(nil, single_target: true) do |machine|
+          exit_code = machine.communicate.sudo(command)
```
Comment (brgnepal) [inline lib/vagrant-service-manager/command.rb]: `sudo` only returns exit code.
Previous `block` approach was not good as it was real time data ([check here](https://github.com/mitchellh/vagrant/blob/master/lib/vagrant/plugin/v2/communicator.rb#L95)).

File: lib/vagrant-service-manager/command.rb [hunk 2]
```diff
@@ -266,21 +266,21 @@ def print_vagrant_box_version(script_readable = false)
...
+          unless exit_code.zero?
+            @env.ui.error "#{command} failed"
```
Comment (brgnepal) [inline lib/vagrant-service-manager/command.rb]: Always ready for better error message here.

File: lib/vagrant-service-manager/services/open_shift.rb [hunk 3]
```diff
@@ -10,12 +10,12 @@ def initialize(machine, ui)
       def execute
         full_cmd = "#{@extra_cmd} sccli openshift"
 
-        @machine.communicate.sudo(full_cmd) do |type, data|
-          if type == :stderr
-            @ui.error(data)
-            exit 126
-          end
+        exit_code = @machine.communicate.sudo(full_cmd)
```
Comment (brgnepal) [inline lib/vagrant-service-manager/services/open_shift.rb]: https://github.com/projectatomic/vagrant-service-manager/pull/167/files#r59221836

File: lib/vagrant-service-manager/services/open_shift.rb [hunk 4]
```diff
@@ -10,12 +10,12 @@ def initialize(machine, ui)
...
+        unless exit_code.zero?
+          @env.ui.error "#{full_cmd} failed"
```
Comment (brgnepal) [inline lib/vagrant-service-manager/services/open_shift.rb]: https://github.com/projectatomic/vagrant-service-manager/pull/167/files#r59221943

File: lib/vagrant-service-manager/command.rb (hunk 2 above)
Comment (brgnepal) [inline lib/vagrant-service-manager/command.rb]: Do you this message is better here:

```
$ vagrant service-manager restart openshift
Restarting openshift ...
```

Dot will increment as the stacked commands get execute.

Comment (bexelbie) [inline lib/vagrant-service-manager/command.rb]: Given the nature of the kinds of failures we could get with sccli and how stacked commands are used should we also output stdout?

**Comment by bexelbie** [comment]
Not yet tested, but looks right.  I added one line note: https://github.com/projectatomic/vagrant-service-manager/pull/167/files#r59224134

File: lib/vagrant-service-manager/command.rb (hunk 2 above)
Comment (brgnepal) [inline lib/vagrant-service-manager/command.rb]: @bexelbie , @praveenkumar suggested me not to show stdout output(stacked commands) and let it be black box for users.

Comment (bexelbie) [inline lib/vagrant-service-manager/command.rb]: @budhrg @praveenkumar ok -- but I think we should add a --debug flag to help us later :) I'll open an issue

Comment (brgnepal) [inline lib/vagrant-service-manager/command.rb]: @bexelbie +1 for --debug flag but we need to make sure it should not conflict with [Vagrant `--debug flag`](https://www.vagrantup.com/docs/other/debugging.html). Also, this should be implemented across plugin and should not specific to some command.

File: lib/vagrant-service-manager/command.rb (hunk 1 above)
Comment (LalatenduMohanty) [inline lib/vagrant-service-manager/command.rb]: +1 for machine.communicate.sudo

File: lib/vagrant-service-manager/command.rb (hunk 2 above)
Comment (LalatenduMohanty) [inline lib/vagrant-service-manager/command.rb]: Should we not print the error output when exit code is non-zero? We should pass the failure output to users.

File: lib/vagrant-service-manager/services/open_shift.rb [hunk 5]
```diff
@@ -10,12 +10,12 @@ def initialize(machine, ui)
...
+          exit 126
         end
+        exit_code
```
Comment (LalatenduMohanty) [inline lib/vagrant-service-manager/services/open_shift.rb]: Should we not print the error output when exit code is non-zero? We should pass the failure output to users.

File: lib/vagrant-service-manager/services/open_shift.rb [hunk 6]
```diff
@@ -10,12 +10,12 @@ def initialize(machine, ui)
...
 
-        @machine.communicate.sudo(full_cmd) do |type, data|
-          if type == :stderr
-            @ui.error(data)
-            exit 126
-          end
+        exit_code = @machine.communicate.sudo(full_cmd)
+        unless exit_code.zero?
+          @env.ui.error "#{full_cmd} failed"
+          exit 126
```
Comment (LalatenduMohanty) [inline lib/vagrant-service-manager/services/open_shift.rb]: Should we not print the error output when exit code is non-zero? We should pass the failure output to users.

File: lib/vagrant-service-manager/command.rb (hunk 2 above)
Comment (brgnepal) [inline lib/vagrant-service-manager/command.rb]: @LalatenduMohanty  As I mentioned in [this comment above](https://github.com/projectatomic/vagrant-service-manager/pull/167#discussion_r59221836), `machine.communicate.sudo` will only return exit code.

Comment (LalatenduMohanty) [inline lib/vagrant-service-manager/command.rb]: @budhrg ok I missed that earlier .  I am not ok with a code which mask failure messages. As this will make debugging failures difficult for an user. Also we do not know when the --debug will land in VSM.

Comment (brgnepal) [inline lib/vagrant-service-manager/command.rb]: @LalatenduMohanty Do you think this would make debugging easier?
Instead of exiting with 126 (blindly), let return the `exit_code` that `machine.communicate.sudo(command)` is returning.
This `exit_code` is same as the one which is returned by `sccli`. Then, we can interpret this `exit_code` in context of `sccli`.

**Comment by praveenkumar** [comment]
I would still prefer to use `systemctl` for restart services instead of `sccli` until it become more stable.

File: lib/vagrant-service-manager/command.rb (hunk 2 above)
Comment (LalatenduMohanty) [inline lib/vagrant-service-manager/command.rb]: @budhrg That would not solve the issue I raised. The question is what we expect the user to do when starting/restarting of OpenShift fails through VSM? IMO if VSM is running the commands and we are getting errors , it should propagate the errors to users

Comment (LalatenduMohanty) [inline lib/vagrant-service-manager/command.rb]: I think we should use something equivalent of below in Vagrant

```
require "open3"

  Open3.popen3('nroff -man') { |stdin, stdout, stderr| ... }
```

OR

```
require 'open3'

stdout, stdeerr, status = Open3.capture3("ls")

puts stdout
```

Comment (brgnepal) [inline lib/vagrant-service-manager/command.rb]:
```
machine.communicate.sudo(cmd) do |type, data|
```

https://github.com/mitchellh/vagrant/blob/master/lib/vagrant/plugin/v2/communicator.rb#L95
This code gives me `type` (either stdout, stderr etc) and data it holds in realtime.
Can we use of this ?

Comment (brgnepal) [inline lib/vagrant-service-manager/command.rb]: > require 'open3'
> stdout, stdeerr, status = Open3.capture3("ls")
> puts stdout

This code looks like hack over tradition Vagrant way to get streams which I mentioned [in this comment](https://github.com/projectatomic/vagrant-service-manager/pull/167#discussion_r59328368) and I wouldn't like to vote for it.

Comment (LalatenduMohanty) [inline lib/vagrant-service-manager/command.rb]: @budhrg loooks like thats the nearest thing we got in Vagrant methods, so worth a shot

Comment (LalatenduMohanty) [inline lib/vagrant-service-manager/command.rb]: @budhrg with respect to 

```
require 'open3'
stdout, stdeerr, status = Open3.capture3("ls")
puts stdout
```

My comment was this `I think we should use something equivalent of below in Vagrant` i.e. we should use Vagrant methods which can do similar stuff

Comment (brgnepal) [inline lib/vagrant-service-manager/command.rb]: :+1:

**Comment by LalatenduMohanty** [comment]
Only for restarting of openshift, at this point using "systemctl" sounds fine.

**Comment by brgnepal** [comment]
@LalatenduMohanty @navidshaikh @bexelbie @praveenkumar :
Updated PR for following changes:
- Use `systemctl` for `restart` services
- Aggregate the errors during command execution and display if command fails with non-zero exit code

**Comment by LalatenduMohanty** [comment]
@budhrg Code LGTM. Testing now

**Comment by LalatenduMohanty** [comment]
Tested this PR with https://github.com/projectatomic/adb-atomic-developer-bundle/pull/335. LGTM
- #166 `vagrant up` for OSE works fine
- #160 i.e. `vagrant service-manager restart openshift` works fine. 

this PR does not fix #163. I am mentioning it because of @budhrg's comment about it i.e. https://github.com/projectatomic/vagrant-service-manager/pull/167#issue-147459748

Just to add #163 is not a blocker. So we can move forward with merging the patch .

```
[root@dhcp35-203 rhel-ose]# vagrant up
xxxxxxxxxxxxxxx
==> default: Registering box with vagrant-registration...
    default: Would you like to register the system now (default: yes)? [y|n]n
==> default: Copying TLS certificates to /home/cdk_08Apr16.1/cdk/components/rhel/rhel-ose/.vagrant/machines/default/libvirt/docker
==> default: Rsyncing folder: /home/cdk_08Apr16.1/cdk/components/rhel/rhel-ose/ => /vagrant
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Successfully started and provisioned VM with 2 cores and 3072 MB of memory.
==> default: To modify the number of cores and/or available memory set the environment variables
==> default: VM_CPU respectively VM_MEMORY.
==> default: You can now access the OpenShift console on: https://10.1.2.2:8443/console
==> default: To use OpenShift CLI, run:
==> default: $ vagrant ssh
==> default: $ oc login 10.1.2.2:8443
==> default: Configured users are (<username>/<password>):
==> default: openshift-dev/devel
==> default: admin/admin
==> default: If you have the oc client library on your host, you can also login from your host.
```

```
root@dhcp35-203 rhel-ose]# vagrant service-manager restart openshift

[root@dhcp35-203 rhel-ose]# vagrant ssh
Last login: Tue Apr 12 04:16:31 2016 from 192.168.121.1
[vagrant@rhel-cdk ~]$ systemctl status openshift
● openshift.service - Docker Application Container for OpenShift
   Loaded: loaded (/usr/lib/systemd/system/openshift.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2016-04-12 04:17:46 EDT; 33s ago
     Docs: https://docs.openshift.org/
  Process: 14421 ExecStop=/usr/bin/sh -c /opt/adb/openshift/openshift_stop (code=exited, status=0/SUCCESS)
  Process: 14483 ExecStartPost=/usr/bin/sh /opt/adb/openshift/openshift_provision (code=exited, status=0/SUCCESS)
  Process: 14477 ExecStartPre=/usr/bin/docker rm openshift (code=exited, status=0/SUCCESS)
  Process: 14471 ExecStartPre=/usr/bin/docker stop openshift (code=exited, status=0/SUCCESS)
 Main PID: 14482 (sh)
   Memory: 6.8M
   CGroup: /system.slice/openshift.service
           ├─14482 /usr/bin/sh /opt/adb/openshift/openshift
           └─14517 docker run --name openshift --privileged --net=host --pid=host -w /var/lib/openshift -e KUBECONFIG=/var/lib/openshift/openshift.local.config/master/admin.kubeconfig -v /:/rootfs:ro -v /var/...

```

**Comment by hferentschik** [comment]
Nice, so we have a way forward. Does this mean we just need a new service-manager release? 1.0.1?

**Comment by praveenkumar** [comment]
> Nice, so we have a way forward. Does this mean we just need a new service-manager release? 1.0.1?

Yes that is the plan, after this fix we will have new release of VSM and then updated zip.

**Comment by praveenkumar** [comment]
LGTM I also tested it out and works as expected.

File: lib/vagrant-service-manager/command.rb [hunk 7]
```diff
@@ -266,21 +265,17 @@ def print_vagrant_box_version(script_readable = false)
...
-        end
-
-        with_target_vms(nil, { single_target: true}) do |machine|
-          machine.communicate.execute(command) do |type, error|
-            if type == :stderr
-              @env.ui.error(error)
-              exit 126
-            end
+        errors = []
+        command = "systemctl restart #{service}"
```
Comment (navidshaikh) [inline lib/vagrant-service-manager/command.rb]: this will break the case when user enters

```
$ vagrant service-manager restart k8s
```

`k8s` is not a systemd service name. If one wants to restart k8s, there are bunch of services needed to be configured.

Check steps to configure kuberentes https://github.com/projectatomic/adb-utils/blob/master/utils/sccli.sh#L6

Also, we should provide the option for user to either say `k8s` or `kubernetes` and we understand it.

Comment (brgnepal) [inline lib/vagrant-service-manager/command.rb]: @navidshaikh Does this means `sccli` is recommanded for 'k8s' as it handles all services in the background?

Comment (praveenkumar) [inline lib/vagrant-service-manager/command.rb]: @navidshaikh no it will not break restart because once your service is setup then user can use `systemctl` to do restart. It is one time setting which `sccli` do nothing else. One check you folks can add that if a user doing `restart` to a non-active service then instead trying to do systemctl restart put a warn message to user '{service} is not running' please run service first before restarting.

Comment (navidshaikh) [inline lib/vagrant-service-manager/command.rb]: kubernetes setup consist of a master and minions. In ADB / CDK, we have a single node setup where master and minion are configured on same node.

For master node, there are following services which are needed to be configured
1. etcd 
2. kube-apiserver 
3. kube-controller-manager 
4. kube-scheduler

and for minion
1. kube-proxy
2. kubelet
3. docker

The sequence of commands to be executed for configuring kubernetes service is written in sccli.
If we do not want to use sccli, we need to execute those commands in plugin.

Comment (brgnepal) [inline lib/vagrant-service-manager/command.rb]: @praveenkumar @LalatenduMohanty Thoughts?

Comment (LalatenduMohanty) [inline lib/vagrant-service-manager/command.rb]: `vagrant service-manager restart k8s` should work and that needs to execute `sccli k8s` . This was working prior to this PR and it should work post this PR too.

Comment (navidshaikh) [inline lib/vagrant-service-manager/command.rb]: > and that needs to execute sccli k8s

Are we still saying we use `sccli` ? Even if @praveenkumar asking multiple times not to use it? https://github.com/projectatomic/vagrant-service-manager/pull/167#issuecomment-208723903
We can implement series of commands needed for kube services in VSM itself.

**Comment by LalatenduMohanty** [comment]
LGTM

File: lib/vagrant-service-manager/command.rb [hunk 8]
```diff
@@ -266,21 +266,24 @@ def print_vagrant_box_version(script_readable = false)
...
+
+        with_target_vms(nil, single_target: true) do |machine|
+          exit_code = machine.communicate.sudo(command) do |type, error|
+            errors << error if type == :stderr
+          end
+          unless exit_code.zero?
+            @env.ui.error errors.join("\n")
+            exit exit_code
           end
+          exit_code
```
Comment (navidshaikh) [inline lib/vagrant-service-manager/command.rb:286]: Although we do not need to explicitly return exit_code here (whose value would be `0`) as this will be returned by default, but okay!

File: lib/vagrant-service-manager/command.rb (hunk 7 above)
Comment (bexelbie) [inline lib/vagrant-service-manager/command.rb]: I believe we should really be relying on sccli to contain all of the knowledge about a service.  If we want to be using `systemctl restart` then we should have sccli smart enough to do that.  Perhaps we should just extend sccli to accept "start" and "restart" as commands.  The complexity of building the interface seems easier to maintain than splitting the application lifecycle management across multiple programs and repositories.

Regarding "k8s" I believe we should drop support for this term.  It isn't a system term and it isn't helping us to have to do adhoc translation.  If we don't drop it, then it should be up to sccli to do the right thing .. not vagrant-service-manager.

**Comment by navidshaikh** [comment]
LGTM
